//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.IISChargeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.thatindigogirl.com/samples/2006/06", ConfigurationName="IISChargeService.IAdminService")]
    public interface IAdminService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/IsValidUser", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/IsValidUserResponse")]
        bool IsValidUser(long username, string password, bool isOperator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/IsValidUser", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/IsValidUserResponse")]
        System.Threading.Tasks.Task<bool> IsValidUserAsync(long username, string password, bool isOperator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddNewAgency", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddNewAgencyResponse")]
        bool AddNewAgency(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    string storename, 
                    int creditbalance, 
                    string storetell, 
                    string storetype, 
                    string storeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddNewAgency", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddNewAgencyResponse")]
        System.Threading.Tasks.Task<bool> AddNewAgencyAsync(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    string storename, 
                    int creditbalance, 
                    string storetell, 
                    string storetype, 
                    string storeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddNewOperator", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddNewOperatorRespons" +
            "e")]
        bool AddNewOperator(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddNewOperator", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddNewOperatorRespons" +
            "e")]
        System.Threading.Tasks.Task<bool> AddNewOperatorAsync(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AgenciesList", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AgenciesListResponse")]
        CompanyBussinesLayer.IISChargeService.ChargeTable AgenciesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AgenciesList", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AgenciesListResponse")]
        System.Threading.Tasks.Task<CompanyBussinesLayer.IISChargeService.ChargeTable> AgenciesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/GetAgencyInformation", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/GetAgencyInformationR" +
            "esponse")]
        CompanyBussinesLayer.IISChargeService.ChargeTable GetAgencyInformation(long username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/GetAgencyInformation", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/GetAgencyInformationR" +
            "esponse")]
        System.Threading.Tasks.Task<CompanyBussinesLayer.IISChargeService.ChargeTable> GetAgencyInformationAsync(long username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/EditAgencyInformation" +
            "", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/EditAgencyInformation" +
            "Response")]
        bool EditAgencyInformation(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    string storename, 
                    int creditbalance, 
                    string storetell, 
                    string storetype, 
                    string storeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/EditAgencyInformation" +
            "", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/EditAgencyInformation" +
            "Response")]
        System.Threading.Tasks.Task<bool> EditAgencyInformationAsync(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    string storename, 
                    int creditbalance, 
                    string storetell, 
                    string storetype, 
                    string storeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/OperatorsList", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/OperatorsListResponse" +
            "")]
        CompanyBussinesLayer.IISChargeService.ChargeTable OperatorsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/OperatorsList", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/OperatorsListResponse" +
            "")]
        System.Threading.Tasks.Task<CompanyBussinesLayer.IISChargeService.ChargeTable> OperatorsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/GetOperatorInformatio" +
            "n", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/GetOperatorInformatio" +
            "nResponse")]
        CompanyBussinesLayer.IISChargeService.ChargeTable GetOperatorInformation(long username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/GetOperatorInformatio" +
            "n", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/GetOperatorInformatio" +
            "nResponse")]
        System.Threading.Tasks.Task<CompanyBussinesLayer.IISChargeService.ChargeTable> GetOperatorInformationAsync(long username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/EditOperatorInformati" +
            "on", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/EditOperatorInformati" +
            "onResponse")]
        bool EditOperatorInformation(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/EditOperatorInformati" +
            "on", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/EditOperatorInformati" +
            "onResponse")]
        System.Threading.Tasks.Task<bool> EditOperatorInformationAsync(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddCharge", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddChargeResponse")]
        bool AddCharge();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddCharge", ReplyAction="http://www.thatindigogirl.com/samples/2006/06/IAdminService/AddChargeResponse")]
        System.Threading.Tasks.Task<bool> AddChargeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : Company.IISChargeService.IAdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<Company.IISChargeService.IAdminService>, Company.IISChargeService.IAdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsValidUser(long username, string password, bool isOperator) {
            return base.Channel.IsValidUser(username, password, isOperator);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidUserAsync(long username, string password, bool isOperator) {
            return base.Channel.IsValidUserAsync(username, password, isOperator);
        }
        
        public bool AddNewAgency(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    string storename, 
                    int creditbalance, 
                    string storetell, 
                    string storetype, 
                    string storeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues) {
            return base.Channel.AddNewAgency(username, password, firstname, lastname, fathername, gender, birthdate, certificatecode, certificateplace, mobilenum, email, homepostalcode, homeaddress, storename, creditbalance, storetell, storetype, storeaddress, signupdate, lasteditdate, lasteditedby, statues);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewAgencyAsync(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    string storename, 
                    int creditbalance, 
                    string storetell, 
                    string storetype, 
                    string storeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues) {
            return base.Channel.AddNewAgencyAsync(username, password, firstname, lastname, fathername, gender, birthdate, certificatecode, certificateplace, mobilenum, email, homepostalcode, homeaddress, storename, creditbalance, storetell, storetype, storeaddress, signupdate, lasteditdate, lasteditedby, statues);
        }
        
        public bool AddNewOperator(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues) {
            return base.Channel.AddNewOperator(username, password, firstname, lastname, fathername, gender, birthdate, certificatecode, certificateplace, mobilenum, email, homepostalcode, homeaddress, signupdate, lasteditdate, lasteditedby, statues);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewOperatorAsync(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues) {
            return base.Channel.AddNewOperatorAsync(username, password, firstname, lastname, fathername, gender, birthdate, certificatecode, certificateplace, mobilenum, email, homepostalcode, homeaddress, signupdate, lasteditdate, lasteditedby, statues);
        }
        
        public CompanyBussinesLayer.IISChargeService.ChargeTable AgenciesList() {
            return base.Channel.AgenciesList();
        }
        
        public System.Threading.Tasks.Task<CompanyBussinesLayer.IISChargeService.ChargeTable> AgenciesListAsync() {
            return base.Channel.AgenciesListAsync();
        }
        
        public CompanyBussinesLayer.IISChargeService.ChargeTable GetAgencyInformation(long username) {
            return base.Channel.GetAgencyInformation(username);
        }
        
        public System.Threading.Tasks.Task<CompanyBussinesLayer.IISChargeService.ChargeTable> GetAgencyInformationAsync(long username) {
            return base.Channel.GetAgencyInformationAsync(username);
        }
        
        public bool EditAgencyInformation(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    string storename, 
                    int creditbalance, 
                    string storetell, 
                    string storetype, 
                    string storeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues) {
            return base.Channel.EditAgencyInformation(username, password, firstname, lastname, fathername, gender, birthdate, certificatecode, certificateplace, mobilenum, email, homepostalcode, homeaddress, storename, creditbalance, storetell, storetype, storeaddress, signupdate, lasteditdate, lasteditedby, statues);
        }
        
        public System.Threading.Tasks.Task<bool> EditAgencyInformationAsync(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    string storename, 
                    int creditbalance, 
                    string storetell, 
                    string storetype, 
                    string storeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues) {
            return base.Channel.EditAgencyInformationAsync(username, password, firstname, lastname, fathername, gender, birthdate, certificatecode, certificateplace, mobilenum, email, homepostalcode, homeaddress, storename, creditbalance, storetell, storetype, storeaddress, signupdate, lasteditdate, lasteditedby, statues);
        }
        
        public CompanyBussinesLayer.IISChargeService.ChargeTable OperatorsList() {
            return base.Channel.OperatorsList();
        }
        
        public System.Threading.Tasks.Task<CompanyBussinesLayer.IISChargeService.ChargeTable> OperatorsListAsync() {
            return base.Channel.OperatorsListAsync();
        }
        
        public CompanyBussinesLayer.IISChargeService.ChargeTable GetOperatorInformation(long username) {
            return base.Channel.GetOperatorInformation(username);
        }
        
        public System.Threading.Tasks.Task<CompanyBussinesLayer.IISChargeService.ChargeTable> GetOperatorInformationAsync(long username) {
            return base.Channel.GetOperatorInformationAsync(username);
        }
        
        public bool EditOperatorInformation(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues) {
            return base.Channel.EditOperatorInformation(username, password, firstname, lastname, fathername, gender, birthdate, certificatecode, certificateplace, mobilenum, email, homepostalcode, homeaddress, signupdate, lasteditdate, lasteditedby, statues);
        }
        
        public System.Threading.Tasks.Task<bool> EditOperatorInformationAsync(
                    long username, 
                    string password, 
                    string firstname, 
                    string lastname, 
                    string fathername, 
                    string gender, 
                    string birthdate, 
                    string certificatecode, 
                    string certificateplace, 
                    string mobilenum, 
                    string email, 
                    string homepostalcode, 
                    string homeaddress, 
                    System.DateTime signupdate, 
                    System.DateTime lasteditdate, 
                    long lasteditedby, 
                    bool statues) {
            return base.Channel.EditOperatorInformationAsync(username, password, firstname, lastname, fathername, gender, birthdate, certificatecode, certificateplace, mobilenum, email, homepostalcode, homeaddress, signupdate, lasteditdate, lasteditedby, statues);
        }
        
        public bool AddCharge() {
            return base.Channel.AddCharge();
        }
        
        public System.Threading.Tasks.Task<bool> AddChargeAsync() {
            return base.Channel.AddChargeAsync();
        }
    }
}
